default: &default 
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Numb3r33 
development: 
  <<: *default
  database: grocery-shopping_development
test:
  <<: *default
  database: grocery-shopping_test
// production:
//   <<: *default
//   database: grocery-shopping_production
//   username: grocery-shopping
//   password: <%= ENV['grocery-shopping_DATABASE_PASSWORD'] %>